
project_id = "grouwquojmflxkqlwukz"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[realtime]
enabled = true

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[auth]
enabled = true
site_url = "http://localhost:3000"

[auth.email]
enabled = true

[functions]
[functions.article-chat]
verify_jwt = true
[functions.speech-to-text]
verify_jwt = true
[functions.text-to-speech]
verify_jwt = true
